# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(728, 522)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.qLabel_Language = QtWidgets.QLabel(self.centralwidget)
        self.qLabel_Language.setObjectName("qLabel_Language")
        self.verticalLayout_2.addWidget(self.qLabel_Language)
        self.qComboBox_Language = QtWidgets.QComboBox(self.centralwidget)
        self.qComboBox_Language.setObjectName("qComboBox_Language")
        self.verticalLayout_2.addWidget(self.qComboBox_Language)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.qLabel_Speed = QtWidgets.QLabel(self.centralwidget)
        self.qLabel_Speed.setObjectName("qLabel_Speed")
        self.horizontalLayout.addWidget(self.qLabel_Speed)
        self.qLabel_SpeedValue = QtWidgets.QLabel(self.centralwidget)
        self.qLabel_SpeedValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.qLabel_SpeedValue.setObjectName("qLabel_SpeedValue")
        self.horizontalLayout.addWidget(self.qLabel_SpeedValue)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.qSlider_SpeedValue = QtWidgets.QSlider(self.centralwidget)
        self.qSlider_SpeedValue.setMinimum(25)
        self.qSlider_SpeedValue.setMaximum(400)
        self.qSlider_SpeedValue.setPageStep(0)
        self.qSlider_SpeedValue.setProperty("value", 100)
        self.qSlider_SpeedValue.setOrientation(QtCore.Qt.Horizontal)
        self.qSlider_SpeedValue.setObjectName("qSlider_SpeedValue")
        self.verticalLayout_2.addWidget(self.qSlider_SpeedValue)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.qLable_Voice = QtWidgets.QLabel(self.centralwidget)
        self.qLable_Voice.setObjectName("qLable_Voice")
        self.verticalLayout.addWidget(self.qLable_Voice)
        self.qComboBox_Voice = QtWidgets.QComboBox(self.centralwidget)
        self.qComboBox_Voice.setObjectName("qComboBox_Voice")
        self.verticalLayout.addWidget(self.qComboBox_Voice)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.qLabel_Pitch = QtWidgets.QLabel(self.centralwidget)
        self.qLabel_Pitch.setObjectName("qLabel_Pitch")
        self.horizontalLayout_3.addWidget(self.qLabel_Pitch)
        self.qLabel_PitchValue = QtWidgets.QLabel(self.centralwidget)
        self.qLabel_PitchValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.qLabel_PitchValue.setObjectName("qLabel_PitchValue")
        self.horizontalLayout_3.addWidget(self.qLabel_PitchValue)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.qSlider_Pitch = QtWidgets.QSlider(self.centralwidget)
        self.qSlider_Pitch.setMinimum(-200)
        self.qSlider_Pitch.setMaximum(200)
        self.qSlider_Pitch.setOrientation(QtCore.Qt.Horizontal)
        self.qSlider_Pitch.setObjectName("qSlider_Pitch")
        self.verticalLayout.addWidget(self.qSlider_Pitch)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.qTextEdit_Content = QtWidgets.QTextEdit(self.centralwidget)
        self.qTextEdit_Content.setObjectName("qTextEdit_Content")
        self.verticalLayout_3.addWidget(self.qTextEdit_Content)
        self.qButton_Speak = QtWidgets.QPushButton(self.centralwidget)
        self.qButton_Speak.setObjectName("qButton_Speak")
        self.verticalLayout_3.addWidget(self.qButton_Speak)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 728, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.qLabel_Language.setText(_translate("MainWindow", "Language"))
        self.qLabel_Speed.setText(_translate("MainWindow", "Speed"))
        self.qLabel_SpeedValue.setText(_translate("MainWindow", "1"))
        self.qLable_Voice.setText(_translate("MainWindow", "Voice"))
        self.qLabel_Pitch.setText(_translate("MainWindow", "Pitch"))
        self.qLabel_PitchValue.setText(_translate("MainWindow", "0"))
        self.qButton_Speak.setText(_translate("MainWindow", "Speak"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
